USE loja;
CREATE TABLE IF NOT EXISTS ContaReceber(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FaturaVendaID INT,
	DataConta DATE NOT NULL,
	DataVencimento DATE NOT NULL,
	Valor DECIMAL(18,2) NOT NULL,
	Situacao ENUM('1','2','3') NOT NULL,
	Cliente_ID INT
);
CREATE TABLE IF NOT EXISTS Cliente(
ID int AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(80) NOT NULL,
CPF CHAR (11) NOT NULL,
Celular CHAR(11),
EndLogradouro VARCHAR(100) NOT NULL,
EndNumero VARCHAR(10) NOT NULL,
EndMunicipio INT NOT NULL,
EndCEP CHAR (8),
Municipio_ID INT
);
CREATE TABLE IF NOT EXISTS Municipio(
ID int AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(80) NOT NULL,
codIBGE INT NOT NULL,
Estado_ID INT
);
CREATE TABLE IF NOT EXISTS Estado (
ID INT AUTO_INCREMENT PRIMARY KEY,
Nome VARCHAR(50) NOT NULL,
UF CHAR(2) NOT NULL
);



ALTER TABLE ContaReceber
	ADD CONSTRAINT FK_ClienteID
    FOREIGN KEY (Cliente_ID) REFERENCES cliente(id);

ALTER TABLE Cliente
	ADD CONSTRAINT FK_MunicipioID
    FOREIGN KEY (Municipio_ID) REFERENCES municipio(id);
    
    ALTER TABLE municipio
	ADD CONSTRAINT FK_EstadoID
    FOREIGN KEY (Estado_ID) REFERENCES estado(id);